version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  assignees:
  - bryanjos
  ignore:
  - dependency-name: ex_doc
    versions:
    - 0.23.0
    - 0.24.0
    - 0.24.1
    - 0.24.2
  - dependency-name: excoveralls
    versions:
    - 0.13.4
    - 0.14.0
  - dependency-name: jason
    versions:
    - 1.2.2
  - dependency-name: stream_data
    versions:
    - 0.5.0
